#pragma once
#include <string>
#include <vector>
#include <memory>
#include "DatasetAR.h"
#include "ARPoly.h"
#include "ARSeq.h"
#include "Seq.h"


/*
 *  Dataset generated by autoregressive process
 */
class DatasetPoly : public DatasetAR {
protected:
    /*
     *  Member variables
     */
    ARPoly target {};               // salient process

    /*
     *  Helper functions
     */
    void noise_zero() override;
    void noise_one() override;
    void noise_two() override;
    void noise_three() override;
    void noise_four() override;

public:
    /*
     *  Constructors and destructors
     */
    DatasetPoly(std::string, ARPoly);
    DatasetPoly(std::string, ARPoly, unsigned char);
};
